-- Table: public.category

-- DROP TABLE IF EXISTS public.category;

CREATE TABLE IF NOT EXISTS public.category
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    name character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description character varying(2048) COLLATE pg_catalog."default" NOT NULL,
    thumbnail_url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    CONSTRAINT category_pkey PRIMARY KEY (id),
    CONSTRAINT uk46ccwnsi9409t36lurvtyljak UNIQUE (name)
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.category
    OWNER to postgres;

-- Table: public.course

-- DROP TABLE IF EXISTS public.course;

CREATE TABLE IF NOT EXISTS public.course
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    category_id bigint NOT NULL,
    mentor_id bigint NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description character varying(4096) COLLATE pg_catalog."default" NOT NULL,
    thumbnail_url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    video_url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    price double precision NOT NULL,
    average_rating double precision NOT NULL,
    students_count integer NOT NULL,
    is_public boolean NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    CONSTRAINT course_pkey PRIMARY KEY (id),
    CONSTRAINT ukmsgoex7rold2eqqf1cllhk02i UNIQUE (title),
    CONSTRAINT fkkyes7515s3ypoovxrput029bh FOREIGN KEY (category_id)
        REFERENCES public.category (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.course
    OWNER to postgres;

-- Table: public.module

-- DROP TABLE IF EXISTS public.module;

CREATE TABLE IF NOT EXISTS public.module
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    course_id bigint NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description character varying(1024) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    CONSTRAINT module_pkey PRIMARY KEY (id),
    CONSTRAINT fkfq09oddpwjoxcirvkh9vnfnsg FOREIGN KEY (course_id)
        REFERENCES public.course (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.module
    OWNER to postgres;

-- Table: public.lecture

-- DROP TABLE IF EXISTS public.lecture;

CREATE TABLE IF NOT EXISTS public.lecture
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    module_id bigint NOT NULL,
    title character varying(255) COLLATE pg_catalog."default" NOT NULL,
    description character varying(1024) COLLATE pg_catalog."default" NOT NULL,
    attachment_url character varying(255) COLLATE pg_catalog."default" NOT NULL,
    is_public boolean NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    CONSTRAINT lecture_pkey PRIMARY KEY (id),
    CONSTRAINT fki5y9gc948ftwi1vwwtlp11tfr FOREIGN KEY (module_id)
        REFERENCES public.module (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.lecture
    OWNER to postgres;

-- Table: public.review

-- DROP TABLE IF EXISTS public.review;

CREATE TABLE IF NOT EXISTS public.review
(
    id bigint NOT NULL GENERATED BY DEFAULT AS IDENTITY ( INCREMENT 1 START 1 MINVALUE 1 MAXVALUE 9223372036854775807 CACHE 1 ),
    course_id bigint NOT NULL,
    student_id bigint NOT NULL,
    rating integer NOT NULL,
    comment character varying(255) COLLATE pg_catalog."default" NOT NULL,
    created_at timestamp(6) without time zone,
    updated_at timestamp(6) without time zone,
    CONSTRAINT review_pkey PRIMARY KEY (id),
    CONSTRAINT fkprox8elgnr8u5wrq1983degk FOREIGN KEY (course_id)
        REFERENCES public.course (id) MATCH SIMPLE
        ON UPDATE NO ACTION
        ON DELETE NO ACTION
)

TABLESPACE pg_default;

ALTER TABLE IF EXISTS public.review
    OWNER to postgres;