INSERT INTO public.category(
	id, name, description, thumbnail_url, created_at, updated_at)
	VALUES (DEFAULT, 'Software Development', 'Nunc a ipsum vehicula, rutrum risus interdum, convallis lectus. Nullam vehicula felis at fringilla consequat. Aenean in libero facilisis, rutrum mi id, accumsan orci. Etiam et malesuada dolor, non gravida metus. Praesent accumsan risus nec fringilla feugiat. Integer turpis nisi, lobortis eget erat et, tincidunt vulputate nisl. Donec fermentum, libero sit amet ultrices consectetur, neque nisl aliquet turpis, nec ornare est nunc ac ipsum.', 'http://localhost:8084/api/files/download/category-1.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 'Design', 'Proin tristique mi a iaculis semper. Mauris iaculis vitae sem ac ultrices. Praesent molestie fermentum faucibus. Cras odio metus, tempor nec hendrerit id, tincidunt consequat turpis. Nunc et lorem leo. Cras dapibus auctor mi, ut consequat augue condimentum tincidunt. Etiam venenatis lacus non enim fringilla, sed dapibus felis sagittis.', 'http://localhost:8084/api/files/download/category-2.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 'Business Skills', 'Sed at erat risus. Etiam elementum accumsan faucibus. Proin blandit arcu sit amet lectus consequat, dapibus egestas sem pretium. Mauris rhoncus vehicula diam, ac gravida mauris convallis vitae. Maecenas et condimentum ligula, fringilla cursus velit. Interdum et malesuada fames ac ante ipsum primis in faucibus.', 'http://localhost:8084/api/files/download/category-3.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 'Personal Development', 'Mauris fermentum tincidunt finibus. Quisque bibendum tortor non pulvinar eleifend. Proin malesuada elit vitae convallis aliquet. Pellentesque ligula ligula, porttitor eget justo vitae, efficitur iaculis diam. Maecenas ut ex at lectus varius tincidunt. Etiam id ornare sapien. Sed in commodo metus, at hendrerit turpis. Fusce at purus eget purus fringilla commodo vel in odio. Nam ornare nunc quam, non interdum magna dictum eu.', 'http://localhost:8084/api/files/download/category-4.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 'Academic Skills', 'Maecenas quam enim, gravida non magna vitae, tristique vestibulum magna. Quisque tincidunt ornare lectus non commodo. Praesent sit amet tincidunt justo. Donec ut magna at orci suscipit accumsan nec in sem. Donec sit amet odio feugiat, efficitur nisi dictum, ullamcorper ipsum. Proin nec tempor risus. Suspendisse malesuada pulvinar venenatis. Cras at arcu velit. In quis cursus libero, aliquam bibendum justo. Ut venenatis neque mauris, sed sodales lectus imperdiet nec.', 'http://localhost:8084/api/files/download/category-5.jpg', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO public.course(
	id, category_id, mentor_id, title, description, thumbnail_url, video_url, price, average_rating, is_public, created_at, updated_at)
	VALUES (DEFAULT, 1, 1, 'Python Programming: From Beginner to Advanced', 'Nunc quis risus sit amet quam eleifend porttitor ac vitae magna. Ut sed laoreet lectus. Donec accumsan est in risus molestie, non dignissim sem aliquam. Phasellus tincidunt erat nec nisi convallis, sit amet maximus urna hendrerit. Vivamus eget purus sed ante euismod porttitor eu in velit. Aliquam nec justo sapien. Donec vitae viverra turpis, sollicitudin ullamcorper tellus. Proin id mi quam. Nunc efficitur dolor ac mattis facilisis. In a erat at odio rutrum scelerisque.', 'http://localhost:8084/api/files/download/course-1.jpg',
	'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', 29.99, 5, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 1, 1, 'Web Development Bootcamp: HTML, CSS, JavaScript', 'Vivamus nec urna sit amet ligula mattis porttitor eget a leo. Nulla odio odio, facilisis luctus tortor a, tempor imperdiet mauris. Nam velit diam, luctus ac mauris id, euismod convallis odio. Pellentesque sodales, justo eget posuere sodales, leo urna auctor turpis, a venenatis mi lorem non nibh. ', 'http://localhost:8084/api/files/download/course-2.jpg',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', 39.99, 4, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 2, 2, 'Adobe Photoshop Mastery: Professional Techniques', 'Phasellus tempus bibendum libero et aliquet. Vestibulum eget consequat eros, quis vehicula diam. Mauris hendrerit elementum ex eu tristique. Vestibulum elit risus, pulvinar nec dignissim quis, facilisis laoreet mi. In quam enim, euismod vitae sapien ut, tempus aliquet dolor. Sed auctor leo sit amet mauris blandit euismod. Nulla aliquet at diam ac auctor. ', 'http://localhost:8084/api/files/download/course-3.jpg',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', 49.99, 4.5, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 2, 2, 'Introduction to UX/UI Design: Creating User-Centered Interfaces', 'Integer nec nisi mattis, finibus nulla sagittis, malesuada nulla. Nullam venenatis justo sit amet neque suscipit, ut luctus mi mattis. Cras imperdiet varius ipsum sed porta. Vivamus non pellentesque ipsum, sed eleifend purus. Proin tempus lorem fringilla enim euismod, nec finibus ipsum mattis. In hac habitasse platea dictumst. ', 'http://localhost:8084/api/files/download/course-4.jpg',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', 49.99, 5, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 3, 3, 'Project Management Fundamentals: Practical Guide', 'Nunc massa turpis, feugiat sit amet est vitae, volutpat molestie massa. Nam aliquet ex et nulla luctus, a pulvinar nunc volutpat. Phasellus a elit purus. Vivamus vel orci hendrerit, vulputate massa ac, tincidunt metus. Duis sagittis elit ante, nec luctus turpis laoreet quis. Etiam lectus sem, placerat eget est et, ultrices efficitur elit.', 'http://localhost:8084/api/files/download/course-5.jpg',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', 59.99, 3.5, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 3, 3, 'Digital Marketing Strategies: Boost Your Online Presence', 'Vestibulum ultrices ipsum nec leo pulvinar, sit amet placerat sapien ultricies. Pellentesque a tellus maximus, fringilla diam ullamcorper, tristique nisi. Etiam in neque nec odio ullamcorper ultricies quis quis turpis. Suspendisse eget urna tellus. Quisque convallis, enim at pellentesque rhoncus, ante dui molestie quam, in rutrum magna urna in orci. Vestibulum ultricies odio varius mauris tristique, nec eleifend arcu volutpat.', 'http://localhost:8084/api/files/download/course-6.jpg',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', 69.99, 4, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 4, 4, 'Mindfulness Meditation: Finding Inner Peace', 'Donec pretium elit vitae erat aliquam semper. Interdum et malesuada fames ac ante ipsum primis in faucibus. Aliquam erat volutpat. Mauris rutrum pretium velit, a laoreet turpis dapibus eu. Nunc enim justo, sollicitudin nec blandit et, lobortis a risus. Etiam lacinia nibh at feugiat tincidunt. Nulla vel mollis nulla. Quisque consequat lorem tincidunt vehicula ullamcorper.', 'http://localhost:8084/api/files/download/course-7.jpg',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', 99.99, 5, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 4, 4, 'Fitness for Beginners: Build a Healthy Exercise Routine', 'Duis faucibus ligula vitae cursus sagittis. Duis bibendum, nisi quis vulputate mollis, tortor neque consectetur turpis, sed auctor massa libero non dolor. Nullam venenatis hendrerit lacus, et consectetur lacus fringilla vitae. Pellentesque justo augue, faucibus vel libero vel, eleifend pellentesque risus. Nullam suscipit metus at sapien aliquet elementum. In quis bibendum tortor. Nulla egestas sit amet enim nec rutrum. Proin sodales arcu turpis, eget vulputate urna elementum ut.', 'http://localhost:8084/api/files/download/course-8.jpg',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', 89.99, 4.5, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 5, 5, 'Introduction to Astrophysics: Exploring the Universe', 'Quisque eleifend ligula non massa ornare accumsan. Morbi in metus vel sapien tincidunt aliquam a lobortis quam. Praesent mattis, felis at sollicitudin vulputate, sapien dui iaculis odio, et faucibus quam nisl at nisi. Aenean bibendum, libero non venenatis posuere, neque urna lacinia est, ac dapibus dolor metus ac orci. Duis vel ipsum quam. In hac habitasse platea dictumst. Nulla maximus quis purus sit amet venenatis.', 'http://localhost:8084/api/files/download/course-9.jpg',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', 79.99, 3, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 5, 5, 'Learn Spanish: Beginners Guide to Conversational Spanish', 'Cras efficitur turpis a dolor faucibus, id aliquet lacus suscipit. Cras commodo ante leo, in suscipit nulla aliquam nec. Aliquam consequat luctus erat non auctor. Nullam ante justo, sollicitudin vel orci vitae, congue sagittis erat. Etiam egestas maximus pellentesque. Sed quis imperdiet mauris, molestie egestas purus. Cras luctus nibh id sem ultricies lacinia. Integer dictum justo a magna pulvinar placerat.', 'http://localhost:8084/api/files/download/course-10.jpg',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', 39.99, 4, true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO public.module(
	id, course_id, title, description, created_at, updated_at)
	VALUES (DEFAULT, 1, 'Module 1: Introduction to Python and Programming Basics', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 1, 'Module 2: Data Types, Variables, and Operators', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 1, 'Module 3: Control Flow and Loops', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 2, 'Module 1: Introduction to Web Development and HTML Basics', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 2, 'Module 2: Styling with CSS: Layouts and Responsive Design', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 2, 'Module 3: JavaScript Fundamentals: DOM Manipulation and Events', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 3, 'Module 1: Introduction to Photoshop Interface and Tools', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 3, 'Module 2: Advanced Photo Editing Techniques and Retouching', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 3, 'Module 3: Creating Stunning Graphics and Visual Effects', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 4, 'Module 1: Fundamentals of User Experience Design', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 4, 'Module 2: User Interface Design Principles and Best Practices', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 4, 'Module 3: Usability Testing and Design Iteration', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 5, 'Module 1: Introduction to Project Management Concepts and Methodologies', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 5, 'Module 2: Planning and Scheduling Projects Effectively', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 5, 'Module 3: Budgeting, Resource Management, and Risk Assessment', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 6, 'Module 1: Fundamentals of Digital Marketing and Online Strategy', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 6, 'Module 2: Search Engine Optimization (SEO) and Content Marketing', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 6, 'Module 3: Social Media Marketing and Advertising Campaigns', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 7, 'Module 1: Understanding Mindfulness and its Benefits', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 7, 'Module 2: Mindfulness Practices for Stress Reduction', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 7, 'Module 3: Cultivating Compassion and Emotional Well-being', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 8, 'Module 1: Introduction to Fitness and Setting Realistic Goals', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 8, 'Module 2: Basic Exercises for Strength, Cardio, and Flexibility', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 8, 'Module 3: Nutrition Tips for Supporting Your Fitness Journey', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 9, 'Module 1: Overview of Astrophysics and Celestial Bodies', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 9, 'Module 2: Theories of Cosmology and the Big Bang', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 9, 'Module 3: Observational Techniques and Current Research', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 10, 'Module 1: Introduction to Spanish Language and Pronunciation', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 10, 'Module 2: Essential Vocabulary and Basic Sentence Structures', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 10, 'Module 3: Practicing Conversational Skills and Cultural Insights', 'Lorem ipsum dolor.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO public.lecture(
	id, module_id, title, description, attachment_url, is_public, created_at, updated_at)
	VALUES (DEFAULT, 1, 'Lecture 1: What is Python and Why Learn It?', 'Lorem ipsum dolor.',
	'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 1, 'Lecture 2: Installing Python and Setting Up Your Development Environment', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 2, 'Lecture 1: Understanding Data Types: Numbers and Strings', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 2, 'Lecture 2: Working with Variables and Assignments in Python', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 3, 'Lecture 1: Conditional Statements: if, elif, else', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 3, 'Lecture 2: Looping with for and while: Iteration in Python', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 4, 'Lecture 1: Overview of Web Technologies and HTML Structure', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 4, 'Lecture 2: Writing Your First HTML Document: Tags and Elements', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 5, 'Lecture 1: Introduction to CSS: Selectors and Declarations', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 5, 'Lecture 2: Creating Layouts with CSS Grid and Flexbox', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 6, 'Lecture 1: Introduction to JavaScript: Variables, Functions, and Objects', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 6, 'Lecture 2: Manipulating the DOM: Selecting Elements and Changing Content', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 7, 'Lecture 1: Navigating Photoshop: Panels, Tools, and Workspace', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 7, 'Lecture 2: Understanding Layers and Layer Management in Photoshop', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 8, 'Lecture 1: Photo Retouching: Removing Blemishes and Imperfections', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 8, 'Lecture 2: Color Correction and Adjustment Layers in Photoshop', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 9, 'Lecture 1: Creating Vector Graphics with Shape Tools and Paths', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 9, 'Lecture 2: Adding Special Effects: Filters, Blending Modes, and Text Effects', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 10, 'Lecture 1: Introduction to UX Design: Principles and Goals', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 10, 'Lecture 1: Introduction to UX Design: Principles and Goals', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 11, 'Lecture 1: Introduction to UX Design: Principles and Goals', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 11, 'Lecture 1: Introduction to UX Design: Principles and Goals', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 12, 'Lecture 1: Conducting Usability Tests: Methods and Analysis', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 12, 'Lecture 2: Iterative Design Process: Prototyping and User Feedback', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 13, 'Lecture 1: What is Project Management? Roles and Responsibilities', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 13, 'Lecture 2: Project Lifecycle Phases: Initiation, Planning, Execution', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 14, 'Lecture 1: Creating Project Plans: Scope, Timeline, and Deliverables', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 14, 'Lecture 2: Resource Allocation and Risk Management in Project Planning', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 15, 'Lecture 1: Managing Project Budgets: Cost Estimation and Control', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 15, 'Lecture 2: Identifying and Mitigating Project Risks: Strategies and Techniques', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 16, 'Lecture 1: Introduction to Mindfulness: Definition and Origins', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 16, 'Lecture 2: Benefits of Practicing Mindfulness: Mental and Physical Health', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 17, 'Lecture 1: Mindful Breathing and Body Scan Techniques', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 17, 'Lecture 2: Cultivating Mindfulness in Daily Life: Applications and Challenges', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 18, 'Lecture 1: Loving-kindness Meditation: Techniques for Compassion', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 18, 'Lecture 2: Emotional Regulation: Managing Stress and Enhancing Resilience', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 19, 'Lecture 1: Importance of Physical Activity: Benefits and Recommendations', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 19, 'Lecture 2: Setting SMART Goals: Strategies for Achieving Fitness Success', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 20, 'Lecture 1: Strength Training Basics: Exercises and Techniques', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 20, 'Lecture 2: Cardiovascular Fitness: Types of Cardio Workouts and Benefits', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 21, 'Lecture 1: Fundamentals of Nutrition: Macronutrients and Micronutrients', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 21, 'Lecture 2: Meal Planning for Fitness: Balancing Diet and Exercise Goals', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 22, 'Lecture 1: Introduction to Astrophysics: Scope and Importance', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 22, 'Lecture 2: Solar System Overview: Planets, Moons, and Other Bodies', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 23, 'Lecture 1: Big Bang Theory: Origins and Evidence', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 23, 'Lecture 2: Dark Matter and Dark Energy: Unsolved Mysteries of the Universe', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 24, 'Lecture 1: Telescopes and Observatories: Tools of Astrophysical Research', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 24, 'Lecture 2: Current Topics in Astrophysics: Exoplanets, Black Holes, and Beyond', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 25, 'Lecture 1: Spanish Alphabet and Pronunciation Guide', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 25, 'Lecture 2: Basic Vocabulary and Common Phrases in Spanish', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 26, 'Lecture 1: Building Spanish Sentences: Grammar Basics', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 26, 'Lecture 2: Conversational Skills: Introducing Yourself and Asking Questions', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 27, 'Lecture 1: Everyday Conversations: Role-plays and Scenarios', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 27, 'Lecture 2: Cultural Awareness: Understanding Spanish-Speaking Cultures', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 28, 'Lecture 2: Looping with for and while: Iteration in Python', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 28, 'Lecture 2: Looping with for and while: Iteration in Python', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 29, 'Lecture 2: Looping with for and while: Iteration in Python', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 29, 'Lecture 2: Looping with for and while: Iteration in Python', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 30, 'Lecture 2: Looping with for and while: Iteration in Python', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', true, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
    (DEFAULT, 30, 'Lecture 2: Looping with for and while: Iteration in Python', 'Lorem ipsum dolor.',
    'https://www.youtube.com/embed/gfU1iZnjRZM?list=PLBnKlKpPeagl57K9bCw_IXShWQXePnXjY', false, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);

INSERT INTO public.review(
	id, course_id, student_id, rating, comment, created_at, updated_at)
	VALUES (DEFAULT, 1, 6, 5, 'Maecenas nec sem sed mauris efficitur scelerisque non at augue.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 1, 7, 5, 'Etiam faucibus scelerisque condimentum. Nunc a rhoncus risus, vel rutrum purus.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 2, 6, 4, 'Maecenas nec sem sed mauris efficitur scelerisque non at augue.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 2, 7, 4, 'Etiam faucibus scelerisque condimentum. Nunc a rhoncus risus, vel rutrum purus.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 3, 6, 5, 'Maecenas nec sem sed mauris efficitur scelerisque non at augue.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 3, 8, 4, 'Etiam faucibus scelerisque condimentum. Nunc a rhoncus risus, vel rutrum purus.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 4, 7, 5, 'Maecenas nec sem sed mauris efficitur scelerisque non at augue.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 4, 8, 5, 'Etiam faucibus scelerisque condimentum. Nunc a rhoncus risus, vel rutrum purus.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 5, 6, 3, 'Maecenas nec sem sed mauris efficitur scelerisque non at augue.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 5, 7, 4, 'Etiam faucibus scelerisque condimentum. Nunc a rhoncus risus, vel rutrum purus.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 6, 7, 4, 'Maecenas nec sem sed mauris efficitur scelerisque non at augue.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 6, 8, 4, 'Etiam faucibus scelerisque condimentum. Nunc a rhoncus risus, vel rutrum purus.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 7, 6, 5, 'Maecenas nec sem sed mauris efficitur scelerisque non at augue.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 7, 8, 5, 'Etiam faucibus scelerisque condimentum. Nunc a rhoncus risus, vel rutrum purus.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 8, 6, 5, 'Maecenas nec sem sed mauris efficitur scelerisque non at augue.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 8, 7, 4, 'Etiam faucibus scelerisque condimentum. Nunc a rhoncus risus, vel rutrum purus.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 9, 7, 3, 'Maecenas nec sem sed mauris efficitur scelerisque non at augue.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 9, 8, 3, 'Etiam faucibus scelerisque condimentum. Nunc a rhoncus risus, vel rutrum purus.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 10, 6, 4, 'Maecenas nec sem sed mauris efficitur scelerisque non at augue.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
	(DEFAULT, 10, 8, 4, 'Etiam faucibus scelerisque condimentum. Nunc a rhoncus risus, vel rutrum purus.', CURRENT_TIMESTAMP, CURRENT_TIMESTAMP);